services:
  wisedatadb:
    image: postgres:latest
    container_name: wisedatadb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./certs:/var/lib/postgresql/certs
    command: postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/certs/server.crt -c ssl_key_file=/var/lib/postgresql/certs/server.key -c ssl_ca_file=/var/lib/postgresql/certs/rootCA.crt
    ports:
      - "5432:5432"
    networks:
      - wisedata_network

networks:
  wisedata_network:
    